name: PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    strategy:
      matrix:
        os: ['ubuntu-slim']
        node_version: ['24.18.0']
        pnpm_version: ['11.9.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{ matrix.pnpm_version }}
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: false
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check Typings
        run: pnpm run type:check
      - name: Run lint
        run: pnpm run lint
      - name: Run test
        run: pnpm run test:ci
